language: node_js
node_js:
  - "12"

jobs:
  include:
    - stage: cve
      sudo: required
      before_install:
        - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
        - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
        - sudo apt-get update -qq
        - sudo apt-get install -y -qq yarn
      cache:
        yarn: true
      script: bash -c "yarn --version; yarn audit"
